// Auto-generated by sync-jobs-daily.js on 2026-03-15T16:19:28.646Z
// 7 verified active postings

const initialJobs = [
    {
        "id": "greenhouse-stripe-7392697",
        "title": "Staff Product Manager, Link Consumer Product",
        "company": "Stripe",
        "location": "SF, SEA, NY, Remote-US",
        "url": "https://stripe.com/jobs/search?gh_jid=7392697",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "fintech"
    },
    {
        "id": "greenhouse-stripe-7568987",
        "title": "Staff Product Manager, Orchestration Lead",
        "company": "Stripe",
        "location": "SF, NY, SEA, US-Remote",
        "url": "https://stripe.com/jobs/search?gh_jid=7568987",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "fintech"
    },
    {
        "id": "greenhouse-stripe-7550590",
        "title": "Staff Product Manager, Stripe Apps and Extensibility Platform",
        "company": "Stripe",
        "location": "San Francisco, Seattle, NYC, Chicago, Toronto, US- Remote, Canada-Remote",
        "url": "https://stripe.com/jobs/search?gh_jid=7550590",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "fintech"
    },
    {
        "id": "greenhouse-webflow-7658245",
        "title": "Senior Product Designer, Analyze",
        "company": "Webflow",
        "location": "CA Remote (BC & ON only); U.S. Remote",
        "url": "https://job-boards.greenhouse.io/webflow/jobs/7658245",
        "posted_date": "2026-02-26",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "tech"
    },
    {
        "id": "greenhouse-webflow-7287511",
        "title": "Director of Product, Infrastructure and Developer Productivity",
        "company": "Webflow",
        "location": "CA Remote (BC & ON only); U.S. Remote",
        "url": "https://job-boards.greenhouse.io/webflow/jobs/7287511",
        "posted_date": "2026-02-24",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "tech"
    },
    {
        "id": "greenhouse-discord-8348158002",
        "title": "Staff Product Manager, Growth & SEO",
        "company": "Discord",
        "location": "Remote (U.S.)",
        "url": "https://job-boards.greenhouse.io/discord/jobs/8348158002",
        "posted_date": "2026-02-03",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-webflow-7456857",
        "title": "Principal Product Manager, AI",
        "company": "Webflow",
        "location": "CA Remote (BC & ON only); U.S. Remote",
        "url": "https://job-boards.greenhouse.io/webflow/jobs/7456857",
        "posted_date": "2026-01-14",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "tech"
    }
];

// Location eligibility check
function isLocationEligible(location) {
    const loc = location.toLowerCase();
    
    // Remote positions that specify US or have 'remote' without foreign country
    if (loc.includes('remote')) {
        // Explicit remote US
        if (loc.includes('us') || loc.includes('u.s.') || loc.includes('united states')) {
            return true;
        }
        // Just 'Remote' with no other location (assume US)
        if (loc === 'remote') {
            return true;
        }
        // 'Location / Remote' or 'Remote / Location' format with US cities
        if (loc.includes('/')) {
            return true; // Allow hybrid remote positions
        }
    }
    
    // Seattle/WA area (in-office or hybrid)
    if (loc.includes('seattle') || loc.includes('washington') || loc.includes(' wa')) {
        return true;
    }
    
    return false;
}

// Add estimated salary data (APIs don't typically expose this)
initialJobs.forEach(job => {
    // Skip if salary already set
    if (job.salary) return;
    
    const title = job.title.toLowerCase();
    
    // Estimate based on role level
    if (title.includes('director') || title.includes('vp') || title.includes('head of')) {
        job.salary = '$250K - $400K';
    } else if (title.includes('principal') || title.includes('staff')) {
        job.salary = '$220K - $320K';
    } else if (title.includes('senior')) {
        job.salary = '$180K - $280K';
    } else {
        job.salary = '$150K - $250K';
    }
});

// Filter to location-eligible jobs only
const eligibleJobs = initialJobs.filter(job => isLocationEligible(job.location));
