// Auto-generated by discover-jobs-v2.js on 2026-03-15T16:07:33.257Z
// 7 verified active postings (curated search with location + role filters)

const initialJobs = [
    {
        "id": "greenhouse-stripe-7392697",
        "title": "Staff Product Manager, Link Consumer Product",
        "company": "Stripe",
        "location": "SF, SEA, NY, Remote-US",
        "url": "https://stripe.com/jobs/search?gh_jid=7392697",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "fintech"
    },
    {
        "id": "greenhouse-stripe-7568987",
        "title": "Staff Product Manager, Orchestration Lead",
        "company": "Stripe",
        "location": "SF, NY, SEA, US-Remote",
        "url": "https://stripe.com/jobs/search?gh_jid=7568987",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "fintech"
    },
    {
        "id": "greenhouse-stripe-7550590",
        "title": "Staff Product Manager, Stripe Apps and Extensibility Platform",
        "company": "Stripe",
        "location": "San Francisco, Seattle, NYC, Chicago, Toronto, US- Remote, Canada-Remote",
        "url": "https://stripe.com/jobs/search?gh_jid=7550590",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "fintech"
    },
    {
        "id": "greenhouse-webflow-7658245",
        "title": "Senior Product Designer, Analyze",
        "company": "Webflow",
        "location": "CA Remote (BC & ON only); U.S. Remote",
        "url": "https://job-boards.greenhouse.io/webflow/jobs/7658245",
        "posted_date": "2026-02-26",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "tech"
    },
    {
        "id": "greenhouse-webflow-7287511",
        "title": "Director of Product, Infrastructure and Developer Productivity",
        "company": "Webflow",
        "location": "CA Remote (BC & ON only); U.S. Remote",
        "url": "https://job-boards.greenhouse.io/webflow/jobs/7287511",
        "posted_date": "2026-02-24",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "tech"
    },
    {
        "id": "greenhouse-discord-8348158002",
        "title": "Staff Product Manager, Growth & SEO",
        "company": "Discord",
        "location": "Remote (U.S.)",
        "url": "https://job-boards.greenhouse.io/discord/jobs/8348158002",
        "posted_date": "2026-02-03",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-webflow-7456857",
        "title": "Principal Product Manager, AI",
        "company": "Webflow",
        "location": "CA Remote (BC & ON only); U.S. Remote",
        "url": "https://job-boards.greenhouse.io/webflow/jobs/7456857",
        "posted_date": "2026-01-14",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "tech"
    }
];
