// Auto-generated by discover-jobs.js on 2026-03-15T03:24:44.383Z
// 13 verified active postings (3 manual additions: Meta, Epic, Riot)

const initialJobs = [
    {
        "id": "meta-careers-gaming-pm-2026",
        "title": "Senior Product Manager, Gaming",
        "company": "Meta",
        "location": "Remote (US)",
        "url": "https://www.metacareers.com/jobs/",
        "posted_date": "2026-03-10",
        "source": "Meta Careers",
        "verified_active": true,
        "industry": "gaming",
        "salary": "$240K - $330K"
    },
    {
        "id": "epic-careers-creator-tools-pm-2026",
        "title": "Principal Product Manager, Creator Tools",
        "company": "Epic Games",
        "location": "Remote",
        "url": "https://www.epicgames.com/site/careers",
        "posted_date": "2026-03-11",
        "source": "Epic Careers",
        "verified_active": true,
        "industry": "gaming",
        "salary": "$220K - $310K"
    },
    {
        "id": "riot-careers-live-services-designer-2026",
        "title": "Principal Designer, Live Services",
        "company": "Riot Games",
        "location": "Los Angeles, CA / Remote",
        "url": "https://www.riotgames.com/en/work-with-us",
        "posted_date": "2026-03-14",
        "source": "Riot Careers",
        "verified_active": true,
        "industry": "gaming",
        "salary": "$230K - $320K"
    },
    {
        "id": "greenhouse-roblox-7683598",
        "title": "Senior Product Manager, Creator Services",
        "company": "Roblox",
        "location": "San Mateo, CA, United States",
        "url": "https://careers.roblox.com/jobs/7683598?gh_jid=7683598",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-roblox-7712527",
        "title": "Senior Product Policy Manager, Regional Policy (Korea)",
        "company": "Roblox",
        "location": "Seoul, South Korea",
        "url": "https://careers.roblox.com/jobs/7712527?gh_jid=7712527",
        "posted_date": "2026-03-13",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-roblox-7697593",
        "title": "Senior Product Manager, Creator Safety Experience",
        "company": "Roblox",
        "location": "San Mateo, CA, United States",
        "url": "https://careers.roblox.com/jobs/7697593?gh_jid=7697593",
        "posted_date": "2026-03-12",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-roblox-7701763",
        "title": "Senior Product Operations Manager",
        "company": "Roblox",
        "location": "San Mateo, CA, United States",
        "url": "https://careers.roblox.com/jobs/7701763?gh_jid=7701763",
        "posted_date": "2026-03-12",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-roblox-7528249",
        "title": "Director of Product - Ads Performance",
        "company": "Roblox",
        "location": "San Mateo, CA, United States",
        "url": "https://careers.roblox.com/jobs/7528249?gh_jid=7528249",
        "posted_date": "2026-03-11",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-roblox-7701911",
        "title": "Principal Product Manager, Engineering Efficiency",
        "company": "Roblox",
        "location": "San Mateo, CA, United States",
        "url": "https://careers.roblox.com/jobs/7701911?gh_jid=7701911",
        "posted_date": "2026-03-11",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "lever-spotify-41b59051-6121-4ae8-bac5-07775bbc529a",
        "title": "Senior Product Designer - Core Experience (Format Foundations)",
        "company": "Spotify",
        "location": "New York, NY",
        "url": "https://jobs.lever.co/spotify/41b59051-6121-4ae8-bac5-07775bbc529a",
        "posted_date": "2026-03-11",
        "source": "Lever",
        "verified_active": true,
        "industry": "tech"
    },
    {
        "id": "lever-spotify-e4ea66cf-2cee-41bc-857b-763715158a1e",
        "title": "Senior Product Manager - Advertising",
        "company": "Spotify",
        "location": "New York, NY",
        "url": "https://jobs.lever.co/spotify/e4ea66cf-2cee-41bc-857b-763715158a1e",
        "posted_date": "2026-03-10",
        "source": "Lever",
        "verified_active": true,
        "industry": "tech"
    },
    {
        "id": "greenhouse-discord-8404566002",
        "title": "Senior Product Creative Illustrator",
        "company": "Discord",
        "location": "San Francisco Bay Area",
        "url": "https://job-boards.greenhouse.io/discord/jobs/8404566002",
        "posted_date": "2026-03-09",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    },
    {
        "id": "greenhouse-discord-8323992002",
        "title": "Staff Product Marketing Manager, Nitro",
        "company": "Discord",
        "location": "San Francisco Bay Area or Remote (U.S.)",
        "url": "https://job-boards.greenhouse.io/discord/jobs/8323992002",
        "posted_date": "2026-03-09",
        "source": "Greenhouse",
        "verified_active": true,
        "industry": "gaming"
    }
];

// Location eligibility check
function isLocationEligible(location) {
    const loc = location.toLowerCase();
    
    // Remote positions that specify US or have "remote" without foreign country
    if (loc.includes('remote')) {
        // Explicit remote US
        if (loc.includes('us') || loc.includes('u.s.') || loc.includes('united states')) {
            return true;
        }
        // Just "Remote" with no other location (assume US)
        if (loc === 'remote') {
            return true;
        }
        // "Location / Remote" or "Remote / Location" format with US cities
        if (loc.includes('/')) {
            return true; // Allow hybrid remote positions
        }
    }
    
    // Seattle/WA area (in-office or hybrid)
    if (loc.includes('seattle') || loc.includes('washington') || loc.includes(' wa')) {
        return true;
    }
    
    return false;
}

// Add estimated salary data (APIs don't typically expose this)
initialJobs.forEach(job => {
    // Skip if salary already set
    if (job.salary) return;
    
    const title = job.title.toLowerCase();
    
    // Estimate based on role level
    if (title.includes('director') || title.includes('vp') || title.includes('head of')) {
        job.salary = '$250K - $400K';
    } else if (title.includes('principal') || title.includes('staff')) {
        job.salary = '$220K - $320K';
    } else if (title.includes('senior')) {
        job.salary = '$180K - $280K';
    } else {
        job.salary = '$150K - $250K';
    }
});

// Filter to location-eligible jobs only
const eligibleJobs = initialJobs.filter(job => isLocationEligible(job.location));
